### ISSUE TITLE
v0.3.4 published for Ubuntu 20.04 breaks Postgresql12

### ISSUE THREAD

**Issue by nschollnetapp** [microsoft/KeysInUse-OpenSSL#10]
I dont know exactly why but installing v0.3.4 on a Ubuntu 20.04 vm in azure breaks the use of certificates in postgresql12 with the following error:

postgres[30072]: segfault at 0 ip 00007f8f93ec3594 sp 00007ffdcc2cf6d0 error 4 in libcrypto.so.1.1

Downgrading back to v0.3.3 resolves the issue and it is very repeatable.  As a note it looks like the azure agent downgrades this package on its own if you leave it installed.  This was not an easy find and leaving an issue here would help others on my path.

**Comment by mamckee** [comment]
Can you share more details about the crash and/or dumps?

**Comment by mamckee** [comment]
Specifically, if you know which call in libcrypto is crashing or have repro steps I can run too.

**Comment by nschollnetapp** [comment]
Program terminated with signal SIGSEGV, Segmentation fault.
#0  0x00007f4c5f0f5594 in EC_POINT_point2oct () from /lib/x86_64-linux-gnu/libcrypto.so.1.1

**Comment by nschollnetapp** [comment]
I cant share dumps for security reasons but this happens just after postmaster is started so I assume its failing to process the key to start the listener or something like that.

**Comment by mamckee** [comment]
That's fair. It helps narrow things a bit. If I build a dev package, can you validate or share the exact steps I can follow to repro?

Additionally, how did the updated package land on the machine. Did you manually perform an apt-get update or did the azure agent auto-update?

**Comment by mamckee** [comment]
Release rolled back and addressed by #11. Published version now contains the fix.
